export const categories = [
    "All",
    'Epicerie salée',
    'Apéritifs bio',
    'Antipasti',
    'Patés végétaux',
    'Biscuits apéritif bio',
    'Chips',
    'Tacos et tortilla',
    'Biscuits apéritif',
    'Fruits secs bio apéritif',
    'Gressins',
    'Chutney et confit bio',
    'Olives bio',
    'Tartinables salés',
    'Bretzels bio',
    'Riz bio',
    'Riz Basmati, Thai, Jasmin',
    'Riz demi complet',
    'Riz long grain',
    'Riz blanc',
    'Riz rouge, riz noir, riz sauvage',
    'Riz complet',
    'Riz rond',
    'Riz cuisson rapide',
    'Risotto, riz japonais',
    'Riz parfumé',
    'Pâtes bio',
    'Pâtes aux céréales',
    'Pâtes de sarrasin',
    'Pâtes Blanches',
    'Pâtes de maïs',
    'Pâtes de quinoa et riz',
    'Pâtes complètes',
    'Nouilles asiatiques, shirataki',
    'Pâtes demi complètes',
    'Pâtes de légumineuse',
    "Pâtes d'épeautre",
    'Pâtes parfumées',
    'Légumineuses et céréales',
    'Légumineuses',
    'Lentilles',
    'Fèves et haricots secs',
    'Semoule, Boulgour, Couscous',
    'Semoule, polenta',
    'Céréales en grains',
    'Sarrasin, kasha',
    'Pois secs',
    'Soja',
    'Maïs',
    'Millet',
    'Quinoa bio',
    'Boulgour, couscous',
    'Epeautre, kamut',
    'Avoine',
    'Mélanges de légumineuses',
    'Orge',
    'Taboulé',
    'Graines et oléagineux',
    'Graines oléagineuses',
    'Graines de lin',
    'Graines de chia',
    'Graines de courge',
    'Graines de tournesol',
    'Graines de sésame',
    'Graines à germer et mélanges',
    'Graines à germer',
    'Graines de chanvre',
    "Graine d'amarante",
    'Mélanges de graines à germer',
    'Mix de graines oléagineuses',
    'Graine de pavot',
    'Farine, son, fécule',
    'Farine de blé',
    'Farine de légumineuses',
    'Farine de céréales',
    "Farine d'avoine",
    "Farine d'épeautre",
    'Farine de fruits bio',
    'Farine de seigle',
    'Fécule, tapioca',
    'Préparations pour pain, brioche',
    'Farine mélange céréales',
    'Farine de sarrasin',
    'Son de blé',
    'Farine de teff, sorgho',
    'Farine de riz',
    'Farine précuite',
    "Son d'avoine",
    'Farine de maïs, millet',
    'Farine de graines',
    'Pain et biscottes',
    'Pain, pain précuit',
    'Epicerie sucrée',
    'Tartines et biscottes',
    'Tartine craquante, biscotte',
    'Galette riz et céréales',
    'Galette multi céréales',
    'Galette de riz nature',
    'Galette de maïs',
    'Légumes et conserves ',
    'Légumes en conserve',
]

